events_management.settings:
  type: config_object
  label: 'Events Management Settings'
  mapping:
    show_past_events:
      type: boolean
      label: 'Show Past Events'
      description: 'Whether to show past events on the listing page.'
    events_per_page:
      type: integer
      label: 'Events Per Page'
      description: 'Number of events to display per page on the listing page.'
